name: Go Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    uses: ./.github/workflows/go-lint.yml

  test:
    name: test
    needs: lint
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.6'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./... -json > test-report.json

      - name: Upload test report
        if: github.event_name != 'pull_request' && !env.ACT
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-report.json
