name: Go Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    uses: ./.github/workflows/go-lint.yml

  test:
    name: test
    needs: lint
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.6'

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v ./...

      - name: Run Terraform provider tests
        run: go test -v ./...
        env:
          TF_ACC: 1
          SHOPIFY_STORE_DOMAIN: ${{ secrets.SHOPIFY_STORE_DOMAIN }}
          SHOPIFY_STORE_ACCESS_TOKEN: ${{ secrets.SHOPIFY_STORE_ACCESS_TOKEN }}
          SHOPIFY_STORE_API_VERSION: ${{ secrets.SHOPIFY_STORE_API_VERSION }}
